name: Build

on:
  pull_request:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: npm ci

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build
